api_platform:
    mapping:
        paths: [ '%kernel.project_dir%/src/Entity' ]
    patch_formats:
        json: [ 'application/merge-patch+json' ]
    formats:
        jsonld: [ 'application/ld+json' ]
        csv: [ 'text/csv' ]
        json: [ 'application/json' ]
#        xlsx: [ 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' ]
    eager_loading:
        force_eager: false
        fetch_partial: true
    defaults:
        pagination_client_items_per_page: true
        pagination_client_enabled: true

when@dev:
    api_platform:
        formats:
            html: [ 'text/html' ]
        title: 'Limas'
        description: 'The Limas REST API'
#        version: '0.0.1'
        openapi:
            contact:
                name: Lopo
                url: 'https://github.com/Lopo'
                email: 'lopo@losys.eu'
#            termsOfService: 'https://'
#            license:
#                name: ''
#                url: 'https://'
            swagger_ui_extra_configuration:
                filter: true
        swagger:
            api_keys:
                apiKey:
                    name: Authorization
                    type: header

when@prod:
    api_platform:
        enable_swagger_ui: false
        enable_re_doc: false
