api_platform:
    enable_swagger: false
    enable_swagger_ui: false
    enable_re_doc: false
    enable_entrypoint: false
    enable_docs: false
    enable_profiler: false
    mapping:
        paths: [ '%kernel.project_dir%/src/Entity' ]
    patch_formats:
        json: [ 'application/merge-patch+json' ]
    formats:
        jsonld: [ 'application/ld+json' ]
        json: [ 'application/json' ]
        csv: [ 'text/csv' ]
#        xlsx: [ 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' ]
    eager_loading:
        force_eager: false
        fetch_partial: true
    defaults:
        pagination_client_items_per_page: true
        pagination_enabled: true
        pagination_client_enabled: true

when@dev:
    api_platform:
        enable_swagger: true
        enable_docs: true
        formats:
            html: [ 'text/html' ]
        title: 'Limas'
        description: 'The Limas REST API'
#        version: '0.0.1'
        openapi:
            contact:
                name: Lopo
                url: 'https://github.com/Lopo'
                email: 'lopo@losys.eu'
#            termsOfService: 'https://'
#            license:
#                name: ''
#                url: 'https://'
        swagger:
            api_keys:
                apiKey:
                    name: Authorization
                    type: header
