framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            assets/: ''
            vendor/atelierspierrot/famfamfam-silk-sprite/src/: 'famfamfam-silk'
        missing_import_mode: strict

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
