when@test:
    liip_test_fixtures:
        keep_database_and_schema: false
        cache_metadata: true
        cache_db:
#            mysql: 'Liip\TestFixturesBundle\Services\DatabaseBackup\MysqlDatabaseBackup'
    services:
        Limas\Tests\DataFixtures\:
            resource: '%kernel.project_dir%/tests/DataFixtures/*'
            tags: ['doctrine.fixture.orm']
