<?php

return [
	Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
	Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
	Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
	Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true],
	Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
	Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
	Symfony\WebpackEncoreBundle\WebpackEncoreBundle::class => ['all' => true],
	Twig\Extra\TwigExtraBundle\TwigExtraBundle::class => ['all' => true],
	Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
	Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
	Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true, 'test' => true],
	Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
	Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle::class => ['dev' => true, 'test' => true],
	ApiPlatform\Symfony\Bundle\ApiPlatformBundle::class => ['all' => true],
	Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle::class => ['all' => true],
	Lexik\Bundle\JWTAuthenticationBundle\LexikJWTAuthenticationBundle::class => ['all' => true],
	Gesdinet\JWTRefreshTokenBundle\GesdinetJWTRefreshTokenBundle::class => ['all' => true],
	Liip\ImagineBundle\LiipImagineBundle::class => ['all' => true],
	Knp\Bundle\GaufretteBundle\KnpGaufretteBundle::class => ['all' => true],
	Sonata\Exporter\Bridge\Symfony\SonataExporterBundle::class => ['all' => true],
	Liip\FunctionalTestBundle\LiipFunctionalTestBundle::class => ['test' => true],
	Liip\TestFixturesBundle\LiipTestFixturesBundle::class => ['test' => true],
	Limas\Bundle\LimasBundle::class => ['all' => true],
];
