controllers:
    resource:
        path: ../src/Controller/
        namespace: Limas\Controller
    type: attribute

api_login_jwt:
    path: /api/users/jwt
    methods: ['POST']

gesdinet_jwt_refresh_token:
    path: /api/token/refresh

when@dev: &swager_dev
    swagger_ui:
        path: /docs
        controller: api_platform.swagger.action.ui
when@test: *swager_dev
