controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_login_jwt:
    path: /api/users/jwt
    methods: ['POST']

gesdinet_jwt_refresh_token:
    path: /api/token/refresh
