# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

imports:
    - { resource: limas.yaml }

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $limas: '%limas%'
            $liipImagine: '@liip_imagine'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Limas\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Limas\Listener\Deserialize:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest', priority: 2}
        autoconfigure: false
        decorates: 'api_platform.listener.request.deserialize'
        arguments:
            $decorated: '@Limas\Listener\Deserialize.inner'
    Limas\Service\OctoPartService:
        arguments:
            $apiKey: '%env(OCTOPART_APIKEY)%'
            $limit: "@=parameter('limas')['octopart']['limit']"
    Limas\Filter\AdvancedSearchFilter:
        tags:
            - { name: api_platform.doctrine.orm.query_extension.collection }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
